package poc.raviraj.cxfwspoc.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-04-11T15:57:49.892+05:30
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://service.cxfwspoc.raviraj.poc/", name = "helloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
