package poc.raviraj.cxfwspoc.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-04-11T15:57:49.900+05:30
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "helloworld", 
                  wsdlLocation = "http://localhost:9090/helloWorldPort?wsdl",
                  targetNamespace = "http://service.cxfwspoc.raviraj.poc/") 
public class Helloworld_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxfwspoc.raviraj.poc/", "helloworld");
    public final static QName HelloWorldPort = new QName("http://service.cxfwspoc.raviraj.poc/", "helloWorldPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/helloWorldPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Helloworld_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/helloWorldPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Helloworld_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Helloworld_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Helloworld_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Helloworld_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Helloworld_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Helloworld_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "helloWorldPort")
    public HelloWorld getHelloWorldPort() {
        return super.getPort(HelloWorldPort, HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "helloWorldPort")
    public HelloWorld getHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldPort, HelloWorld.class, features);
    }

}
