package poc.raviraj.cxfwspoc.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-04-11T16:05:22.133+05:30
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "mastertypes", 
                  wsdlLocation = "http://localhost:9090/masterTypeServicePort?wsdl",
                  targetNamespace = "http://service.cxfwspoc.raviraj.poc/") 
public class Mastertypes extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxfwspoc.raviraj.poc/", "mastertypes");
    public final static QName MasterTypeServicePort = new QName("http://service.cxfwspoc.raviraj.poc/", "masterTypeServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/masterTypeServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Mastertypes.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/masterTypeServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Mastertypes(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Mastertypes(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Mastertypes() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Mastertypes(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Mastertypes(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Mastertypes(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MasterTypeService
     */
    @WebEndpoint(name = "masterTypeServicePort")
    public MasterTypeService getMasterTypeServicePort() {
        return super.getPort(MasterTypeServicePort, MasterTypeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MasterTypeService
     */
    @WebEndpoint(name = "masterTypeServicePort")
    public MasterTypeService getMasterTypeServicePort(WebServiceFeature... features) {
        return super.getPort(MasterTypeServicePort, MasterTypeService.class, features);
    }

}
