package poc.raviraj.cxfwspoc.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-04-11T16:06:47.418+05:30
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://service.cxfwspoc.raviraj.poc/", name = "userService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "paginated", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.Paginated")
    @WebMethod
    @ResponseWrapper(localName = "paginatedResponse", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.PaginatedResponse")
    public java.util.List<poc.raviraj.gwtapp.shared.User> paginated(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.Save")
    @WebMethod
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.SaveResponse")
    public poc.raviraj.gwtapp.shared.User save(
        @WebParam(name = "arg0", targetNamespace = "")
        poc.raviraj.gwtapp.shared.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.DeleteResponse")
    public poc.raviraj.gwtapp.shared.User delete(
        @WebParam(name = "arg0", targetNamespace = "")
        poc.raviraj.gwtapp.shared.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.Find")
    @WebMethod
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.FindResponse")
    public poc.raviraj.gwtapp.shared.User find(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.FindAll")
    @WebMethod
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.FindAllResponse")
    public java.util.List<poc.raviraj.gwtapp.shared.User> findAll();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllByFirstNameOrLastNameOrUsername", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.FindAllByFirstNameOrLastNameOrUsername")
    @WebMethod
    @ResponseWrapper(localName = "findAllByFirstNameOrLastNameOrUsernameResponse", targetNamespace = "http://service.cxfwspoc.raviraj.poc/", className = "poc.raviraj.cxfwspoc.service.FindAllByFirstNameOrLastNameOrUsernameResponse")
    public java.util.List<poc.raviraj.gwtapp.shared.User> findAllByFirstNameOrLastNameOrUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
